/* code generated by stop_write_code() to produce a
 * stoplist with default contents */

#include "firstinclude.h"

#include "stop.h"

struct stop *stop_new_default(void (*stem)(void *opaque, char *term),
  void *opaque) {
    struct stop *list = stop_new(stem, opaque);
    enum stop_ret ret;
    if (!list) {
        return NULL;
    }

    if ((ret = stop_add_term(list, "across")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "serious")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "forty")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "million")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "vs")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "any")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "consequently")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "after")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "far")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "forth")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "whenever")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "sent")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "eighteen")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "anywhere")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "herein")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "whereas")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "then")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "can")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "and")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "up")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "us")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "seventh")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "billion")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "them")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "herself")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "appear")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "they")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "themselves")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "seventy")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "inward")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "anyhow")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "to")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "seem")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "other")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "perhaps")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "understood")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "considering")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "most")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "eleven")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "specify")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "whereupon")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "would")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "subject")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "whereby")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "some")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "seventeen")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "probably")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "nevertheless")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "does")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "so")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "under")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "really")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "already")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "indicates")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "except")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "among")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "notion")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "more")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "without")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "anything")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "contain")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "with")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "specifying")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "f")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "e")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "d")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "c")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "b")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "a")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "indeed")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "n")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "hereafter")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "been")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "m")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "throughout")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "l")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "k")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "j")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "i")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "h")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "g")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "v")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "u")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "t")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "s")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "r")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "q")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "hardly")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "amongst")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "p")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "o")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "understand")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "z")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "least")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "y")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "indicated")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "few")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "x")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "someone")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "w")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "than")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "if")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "ie")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "almost")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "means")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "may")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "rather")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "misses")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "that")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "ought")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "somehow")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "notional")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "only")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "it")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "is")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "insofar")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "in")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "which")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "half")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "something")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "quite")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "apart")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "he")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "interests")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "relates")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "include")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "howbeit")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "exclusive")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "just")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "missed")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "upon")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "way")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "whether")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "was")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "like")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "sometime")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "related")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "whither")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "go")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "toward")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "all")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "eighth")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "corresponding")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "thereby")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "went")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "should")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "normally")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "whatever")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "eighty")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "allowable")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "whom")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "exclusively")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "containing")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "did")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "thence")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "nowhere")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "whence")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "even")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "another")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "yourselves")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "entire")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "ever")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "might")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "neither")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "whoever")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "although")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "included")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "anybody")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "namely")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "right")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "its")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "ninth")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "between")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "our")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "three")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "self")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "out")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "whereafter")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "relate")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "particularly")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "your")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "includes")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "before")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "thousand")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "therefore")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "said")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "name")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "possible")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "done")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "where")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "never")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "left")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "immediate")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "please")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "hence")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "were")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "still")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "ourselves")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "accordingly")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "many")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "own")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "specified")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "next")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "meanwhile")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "interesting")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "currently")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "since")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "onto")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "see")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "ten")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "beside")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "besides")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "thirty")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "twelve")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "stylish")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "particular")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "well")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "over")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "for")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "or")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "on")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "given")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "respectively")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "secondly")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "mostly")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "hundred")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "somewhere")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "outside")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "their")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "oh")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "of")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "could")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "otherwise")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "contains")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "four")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "however")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "via")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "note")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "she")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "down")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "his")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "thus")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "notions")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "eg")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "therein")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "six")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "used")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "considered")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "wherever")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "from")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "et")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "ex")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "viz")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "uses")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "fourteen")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "subjects")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "hereby")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "sensible")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "downwards")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "nor")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "not")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "now")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "there")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "here")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "do")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "have")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "appears")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "when")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "much")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "inner")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "hers")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "further")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "twenty")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "fifty")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "styling")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "eleventh")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "the")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "styler")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "afterwards")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "into")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "co")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "stylistic")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "including")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "allowed")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "each")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "hereupon")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "consider")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "styled")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "furthermore")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "very")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "during")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "tenth")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "old")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "placed")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "seems")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "beforehand")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "third")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "former")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "missing")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "around")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "while")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "against")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "zero")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "both")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "within")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "provides")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "ninety")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "twelth")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "enough")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "near")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "are")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "sometimes")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "etc")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "wanted")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "these")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "latterly")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "fifth")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "every")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "below")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "behind")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "overall")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "instead")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "thereafter")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "inc")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "got")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "becomes")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "various")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "thoroughly")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "also")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "one")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "value")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "thereupon")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "considers")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "fourth")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "nothing")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "allow")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "want")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "sixteen")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "whole")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "taken")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "you")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "those")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "beyond")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "useful")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "too")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "dozen")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "away")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "what")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "ltd")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "theirs")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "such")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "unto")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "how")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "we")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "inasmuch")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "hitherto")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "thorough")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "roles")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "use")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "same")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "but")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "became")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "plus")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "though")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "always")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "new")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "using")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "entirely")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "no")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "mean")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "had")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "several")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "wherein")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "doing")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "alone")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "me")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "along")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "has")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "my")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "noone")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "fifteen")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "latter")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "seven")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "albeit")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "cannot")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "unless")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "principle")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "allowing")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "allows")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "often")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "seeming")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "lest")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "less")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "nobody")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "through")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "myself")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "above")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "interest")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "get")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "mine")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "somewhat")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "about")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "found")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "must")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "others")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "meaning")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "else")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "be")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "big")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "eight")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "towards")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "will")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "somebody")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "thirteen")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "off")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "nineteen")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "style")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "interested")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "by")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "sup")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "gone")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "having")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "this")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "her")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "because")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "an")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "ours")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "once")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "am")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "notes")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "become")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "necessary")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "at")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "as")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "per")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "nought")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "again")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "yourself")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "usually")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "either")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "why")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "considerable")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "together")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "sixty")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "shall")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "last")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "none")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "sub")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "questionable")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "himself")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "five")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "itself")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "who")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "indicate")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "sixth")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "relatively")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "first")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "anyone")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "nine")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "two")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "moreover")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "example")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "yet")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "little")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "role")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "seemed")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "whose")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "appropriate")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    if ((ret = stop_add_term(list, "until")) != STOP_OK
      && ret != STOP_EEXIST) {
        stop_delete(list);
        return NULL;
    }

    return list;
}

